### ISSUE TITLE
Popup Overlay

### ISSUE THREAD

**Issue by samsoft00** [klinker24/FloatingWindowDemo#1]
Great work... please how do i create a popup overlay like the Talon app twitter message? trying to overide onCreate but didnt work. help

**Comment by klinker24** [comment]
Take a look at the PopupMainActivity class.

It extends MainActivity so that it inherits all of that class's functionality, then it overrides the SetUpWindow() function.

In the original main activity, this setUpWindow() function doesn't do anything, but when you override it in the popup main activity method, you can force it into the windowed mode.

You shouldn't need to override the onCreate() method unless you want to change the layout or something for the popup over the original, fullscreen app.

**Comment by samsoft00** [comment]
@klinker24 thanks for your quick response, what i want to achieve it to have two (2) layout (different), One will be main activity and one will be popup, when button is click in main activity, the popup will be show ontop of the main activity with different layout. Overlaying ontop of the main activity. Like MainActivityPopup in Talcon-for-twitter. Thanks

**Comment by klinker24** [comment]
Oh, you mean like on the tweet viewer or profile viewer.

For this, you should just create a completely separate activity from your main activity and have it use the windowed function from my popup activity by default. Just call that window function in the new popup activity's on create and it will show windowed

You can then use an intent to open that windowed activity, just as you would any other, normal activity

**Comment by samsoft00** [comment]
@klinker24 Sorry, i'm not getting it... is like you're interchanging  some words, Please explain plainly! Thanks

**Comment by klinker24** [comment]
Lol. Thats as plain as I can make it. 

Make a new activity and use the setUpWindow() in its on create method.

Then open that activity like any other, with an intent, after you click the button.

**Comment by samsoft00** [comment]
@klinker24 Smile, I understand now and i've done exactly but the issue right now is to make the Activity Overlay the existing one (For the New Activity to stay ontop of the existing Activity layout where the button was click), i don't want the existing layout to close. how can i achieve that? thanks

**Comment by samsoft00** [comment]
@klinker24 sorry, is working now... my bad, use finish() before the new intent. Thanks, Please can i ask something, can i use Talcon-Twitter-app, add more behavior and functionality and deploy it as my application???
